// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhQcX-X2R0Exo7kylDOr09T6wgWASaIq8',
    appId: '1:733147415742:web:5b435c3f87c82ead870aef',
    messagingSenderId: '733147415742',
    projectId: 'artidirect-305ac',
    authDomain: 'artidirect-305ac.firebaseapp.com',
    storageBucket: 'artidirect-305ac.appspot.com',
    measurementId: 'G-Q13MLL2QXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGHA-e12xOHYi58SEBZvdbL3eQVlY382A',
    appId: '1:733147415742:android:f0ff1e6427cb087e870aef',
    messagingSenderId: '733147415742',
    projectId: 'artidirect-305ac',
    storageBucket: 'artidirect-305ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzREd31v-5V0aITwiJCW6u5wbwz3tngcw',
    appId: '1:733147415742:ios:53d63a38e651bc69870aef',
    messagingSenderId: '733147415742',
    projectId: 'artidirect-305ac',
    storageBucket: 'artidirect-305ac.appspot.com',
    iosClientId: '733147415742-mopq28hm7l5es1pbaf68rb585jo8f0tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectArtDirect',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzREd31v-5V0aITwiJCW6u5wbwz3tngcw',
    appId: '1:733147415742:ios:53d63a38e651bc69870aef',
    messagingSenderId: '733147415742',
    projectId: 'artidirect-305ac',
    storageBucket: 'artidirect-305ac.appspot.com',
    iosClientId: '733147415742-mopq28hm7l5es1pbaf68rb585jo8f0tf.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalProjectArtDirect',
  );
}
